databaseChangeLog:
  - changeSet:
      id: 1739967281622-1
      author: mkUser
      objectQuotingStrategy: QUOTE_ONLY_RESERVED_WORDS
      changes:
        - createTable:
            columns:
              - column:
                  autoIncrement: true
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: pk_attributes
                  name: id
                  type: BIGINT
              - column:
                  constraints:
                    nullable: false
                  name: key
                  type: VARCHAR(255)
              - column:
                  constraints:
                    nullable: false
                  name: value
                  type: VARCHAR(255)
              - column:
                  constraints:
                    nullable: false
                  name: product_id
                  type: BIGINT
            tableName: attributes
  - changeSet:
      id: 1739967281622-2
      author: mkUser
      objectQuotingStrategy: QUOTE_ONLY_RESERVED_WORDS
      changes:
        - createTable:
            columns:
              - column:
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: pk_product_category
                  name: category_id
                  type: BIGINT
              - column:
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: pk_product_category
                  name: product_id
                  type: BIGINT
            tableName: product_category
  - changeSet:
      id: 1739967281622-3
      author: mkUser
      objectQuotingStrategy: QUOTE_ONLY_RESERVED_WORDS
      changes:
        - createTable:
            columns:
              - column:
                  autoIncrement: true
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: pk_product_images
                  name: id
                  type: BIGINT
              - column:
                  constraints:
                    nullable: false
                  name: image_url
                  type: VARCHAR(2048)
              - column:
                  constraints:
                    nullable: false
                  name: product_id
                  type: BIGINT
              - column:
                  name: order_index
                  type: INT
            tableName: product_images
  - changeSet:
      id: 1739967281622-4
      author: mkUser
      objectQuotingStrategy: QUOTE_ONLY_RESERVED_WORDS
      changes:
        - createTable:
            columns:
              - column:
                  autoIncrement: true
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: pk_products
                  name: id
                  type: BIGINT
              - column:
                  constraints:
                    nullable: false
                  name: title
                  type: VARCHAR(255)
              - column:
                  constraints:
                    nullable: false
                  name: description
                  type: TEXT
              - column:
                  constraints:
                    nullable: false
                  name: article
                  type: VARCHAR(255)
              - column:
                  constraints:
                    nullable: false
                  name: price
                  type: DECIMAL(10, 2)
            tableName: products
  - changeSet:
      id: 1739967281622-5
      author: mkUser
      objectQuotingStrategy: QUOTE_ONLY_RESERVED_WORDS
      changes:
        - addForeignKeyConstraint:
            baseColumnNames: product_id
            baseTableName: attributes
            constraintName: FK_ATTRIBUTES_ON_PRODUCT
            referencedColumnNames: id
            referencedTableName: products
  - changeSet:
      id: 1739967281622-6
      author: mkUser
      objectQuotingStrategy: QUOTE_ONLY_RESERVED_WORDS
      changes:
        - addForeignKeyConstraint:
            baseColumnNames: product_id
            baseTableName: product_images
            constraintName: FK_PRODUCT_IMAGES_ON_PRODUCT
            referencedColumnNames: id
            referencedTableName: products
  - changeSet:
      id: 1739967281622-7
      author: mkUser
      objectQuotingStrategy: QUOTE_ONLY_RESERVED_WORDS
      changes:
        - addForeignKeyConstraint:
            baseColumnNames: category_id
            baseTableName: product_category
            constraintName: fk_procat_on_category
            referencedColumnNames: id
            referencedTableName: categories
  - changeSet:
      id: 1739967281622-8
      author: mkUser
      objectQuotingStrategy: QUOTE_ONLY_RESERVED_WORDS
      changes:
        - addForeignKeyConstraint:
            baseColumnNames: product_id
            baseTableName: product_category
            constraintName: fk_procat_on_product
            referencedColumnNames: id
            referencedTableName: products

