name: Deploy to EC2

on:
  push:
    branches: [ "master" ]

env:
  AWS_REGION: eu-north-1
  ECR_REPOSITORY: nordic-nest-api

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build and Push Docker Image
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/v2q6v1m6
          docker build -t ${{ env.ECR_REPOSITORY }} .
          docker tag ${{ env.ECR_REPOSITORY }}:latest public.ecr.aws/v2q6v1m6/${{ env.ECR_REPOSITORY }}:latest
          docker push public.ecr.aws/v2q6v1m6/${{ env.ECR_REPOSITORY }}:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_INSTANCE_IP }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Pull the latest image
            sudo docker pull public.ecr.aws/v2q6v1m6/${{ env.ECR_REPOSITORY }}:latest

            # Stop and remove any existing container
            sudo docker stop ${{ env.ECR_REPOSITORY }} || true
            sudo docker rm ${{ env.ECR_REPOSITORY }} || true
            
            # Create env file on the EC2 instance
            echo "DB_DATASOURCE_URL=${{ secrets.DB_DATASOURCE_URL }}" > env.list
            echo "DB_DATASOURCE_USERNAME=${{ secrets.DB_DATASOURCE_USERNAME }}" >> env.list
            echo "DB_DATASOURCE_PASSWORD=${{ secrets.DB_DATASOURCE_PASSWORD }}" >> env.list
            
            echo "JWT_SECRET=${{ secrets.JWT_SECRET_KEY }}" >> env.list
            echo "JWT_EXPIRATION=${{ secrets.JWT_EXPIRATION }}" >> env.list
            
            echo "AWS_S3_ACCESS_KEY=${{ secrets.AWS_S3_ACCESS_KEY }}" >> env.list
            echo "AWS_S3_SECRETE_ACCESS_KEY=${{ secrets.AWS_S3_SECRETE_ACCESS_KEY }}" >> env.list
            echo "AWS_S3_BUCKET_NAME=${{ secrets.AWS_S3_BUCKET_NAME }}" >> env.list
            echo "AWS_S3_REGION=${{ secrets.AWS_S3_REGION }}" >> env.list
  
            # Run the new container
            sudo docker run -d -p 8080:8080 --name ${{ env.ECR_REPOSITORY }} --env-file env.list public.ecr.aws/v2q6v1m6/${{ env.ECR_REPOSITORY }}:latest